# Hardware Configuration Template
# This file will be generated by nixos-generate-config during installation
# This template shows the expected structure
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # NOTE: This is a TEMPLATE - actual values will be generated during install
  # The installer will detect your:
  # - CPU (AMD/Intel)
  # - Disk layout (NVMe, SATA, etc.)
  # - Boot configuration
  # - Available filesystems

  # Example structure (will be replaced):
  boot = {
    initrd = {
      availableKernelModules = ["nvme" "xhci_pci" "ahci" "usbhid" "sd_mod"];
      kernelModules = [];
    };
    kernelModules = ["kvm-amd"]; # or "kvm-intel" for Intel
    extraModulePackages = [];
  };

  # Filesystems - will be auto-detected
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/XXXX-XXXX";
    fsType = "vfat";
  };

  # Swap - if configured
  swapDevices = [];

  # Hardware settings
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # OR for Intel: hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
